- name: html to pdf
  uses: misaelnieto/web_to_pdf_action@master
  with:
    webPageURL: https://thenewstack.io/graphql-break-free-of-backend-for-frontend-sprawl/
    outputFile: ./resume.pdf
    usePuppeteer: true
    useScreen: true
    pdfOptions: '{"format": "Letter", "margin": {"top": "10mm", "left": "10mm", "right": "10mm", "bottom": "10mm"}}'
